name: Deploy Website ke InfinityFree

on:
  push:
    branches:
      - main  # PPastikan nama branch utama kalian 'main' atau 'master'

jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Ambil kodingan terbaru (Checkout)
      uses: actions/checkout@v4
    
    - name: ðŸ“‚ Upload ke InfinityFree (FTP)
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        # Data dari Screenshot kamu:
        server: ftpupload.net
        username: if0_40507318
        
        # Password diambil dari Secret GitHub (yang dibuat di Langkah 1):
        password: ${{ secrets.FTP_PASSWORD }}
        
        # PENTING: InfinityFree wajib taruh file di dalam folder htdocs
        server-dir: ./htdocs/
        
        # Protokol (biarkan false untuk FTP biasa agar lebih cepat/kompatibel)
        secure: false
